# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    path: homepage
    class: first
  - label: Diensten
    path: dienstenpagina/vestigingsplaats-onderzoek
  - label: Over ABM
    path: over-abm
  - label: Team
    path: team
  - label: Contact
    path: contact 
    class: last
